### PR TITLE
Update Dockerfile.amd64

### PR DESCRIPTION
**Pull request by leakypixel**
New snapserver version

### CODE REVIEW

**Comment by hamishfagg** [comment]
Thanks for this. I will merge this weekend.

Can you please change to update both dockerfiles for snapserver and snapclient?

I was sure I had done this for 0.15 but apparently not - good catch.

**Comment by hamishfagg** [comment]
I have merged my own request which updates to 0.15

**Comment by leakypixel** [comment]
@IVData Sorry for missing this, been on holiday this weekend. Thanks for updating!

**Comment by hamishfagg** [comment]
No worries. If you're using the ARM images I am currently having build issues and they should be sorted soon.

**Pull request closed without merging**
